server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ec2-63-32-248-14.eu-west-1.compute.amazonaws.com:5432/d8iehoo5d7dnc4
    driver-class-name: org.postgresql.Driver
    password: 690911a6d3f46370d368d26a99a5bc648c3c3975c09fca202cb5168088670775
    username: ocysapooyvurkj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  main:
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
springdoc:
  api-docs:
    path: /api-docs

