server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maktab-darsliklari-app
    driver-class-name: org.postgresql.Driver
    password: 4444
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  main:
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
springdoc:
  api-docs:
    path: /api-docs

